project:
  type: website 
  output-dir: docs
  
website: 
  title: "ISEE young 2024 - WS8 - Reproducitiliby"
  description: "Reproductible research and data science practices for young epidemiologist"
  site-url: "https://rstudio-conf-2022.github.io/ggplot2-graphic-design/"
  favicon: "/img/isee-young-logo.png"

  repo-url: https://github.com/ste-tuf/isee-young-ws-reproducibility/
  page-navigation: true
  
  page-footer:
    left: "This page is built with [Quarto](https://quarto.org/)."
    right: "&copy; CC BY-NC, Stéphane Tuffier"
    background: "#0b6fa1"


  navbar: 
    search: true
    pinned: true
    logo: "/img/isee-young-logo.png"
    background: "#0b6fa1"
    align: center

    left:
      - text: Pre-workshop
        menu:
          - text: Installation
            href: content/00_pre-ws.qmd#installation
          - text: Data
            href: content/00_pre-ws.qmd#data
      # - text: Introduction
      #   href: content/01_intro.qmd
      # - text: Activity 1
      #   href: content/02_exercise_1.qmd
      # - text: Activity 2
      #   href: content/03_exercise_2.qmd
    right: 
      - icon: github
        href: https://github.com/ste-tuf/isee-young-ws-reproducibility/
        text: GitHub

format:
  html:
    theme: zephyr
    # css: styles.css
    toc: true
    code-copy: true
    code-overflow: wrap
