---
title: "Introduction"
author: "Stephane Tuffier"
date: 2024-06-05
slide-format: revealjs
---


# Slides

<div>

```{=html}
<iframe class="slide-deck" src="01_slides_intro.html" width="100%" height="500px"></iframe>
```

</div>

# General context 

The ultimate aim of this workshop is to  make you able to start creating data analysis projects that are: 

- self-contained (within a single folder)
- have a record of changes made to the files
- make it easier for others to collaborate
- make it simpler to connect the project with a scientific output like a paper
- to structure analyses to be more reproducible (or at least more easily inspectable).

This is will: 

- improve transparency of your reseach project
- make it easier to share both with your research team but also public, funding agency and other researcher
- facilitate the assessment of the quality of your work including peer review.

Reproducible research is not just about R but more about research practices. We will do many non R things in this workshop.
